# ===================================================================
#                   Database configuration
# ===================================================================

spring:
  liquibase:
    change-log: 'classpath:/db/changelog/changelog.xml'

  jpa:
    hibernate:
      ddl-auto: 'validate'
      show-sql: false
