# ====================================================================================
#
#       Properties that is used by the helloworld backend across
#       all environments
#
# ====================================================================================

