version: "2"
services:
  helloworld-backend-service:
    image: helloworld-backend-service:latest
    environment:
      - SPRING_PROFILES_ACTIVE=local-backend
      - JAVA_OPTS=-agentlib:jdwp=transport=dt_socket,address=8000,suspend=n,server=y
    volumes:
      - "../config/backends/helloworld/application.yml:/opt/app/config/application.yml:ro"
      - "../config/backends/helloworld/application-local-backend.yml:/opt/app/config/application-local-backend.yml:ro"
      - "../config/backends/application.yml:/opt/app/application.yml:ro"
      - "../config/backends/application-local-backend.yml:/opt/app/application-local-backend.yml:ro"

  mycash-accounting-backend-service:
    image: mycash-accounting-backend-service:latest
    environment:
      - SPRING_PROFILES_ACTIVE=local-backend
      - JAVA_OPTS=-agentlib:jdwp=transport=dt_socket,address=8000,suspend=n,server=y
    volumes:
      - "../config/backends/mycash/accounting/application.yml:/opt/app/config/application.yml:ro"
      - "../config/backends/mycash/accounting/application-local-backend.yml:/opt/app/config/application-local-backend.yml:ro"
      - "../config/backends/application.yml:/opt/app/application.yml:ro"
      - "../config/backends/application-local-backend.yml:/opt/app/application-local-backend.yml:ro"

  tel-dev-proxy:
    image: nginx:latest
    volumes:
      - "./nginx/nginx.conf:/etc/nginx/nginx.conf:ro"
      - "./nginx/nginx-cors.conf:/etc/nginx/nginx-cors.conf:ro"
      - "./nginx/nginx-service.conf:/etc/nginx/nginx-service.conf:ro"
    ports:
      - "13200:80"
    links:
      - helloworld-backend-service
      - mycash-accounting-backend-service
